package org.jabref.vimotest.MainTableTests;

/*Generated by MPS */


public class JabRefMainTableViewModelTestSetupImpl extends JabRefMainTableViewModelTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public void SetBibFileTestContext() {
  }
  @Override
  public JabRefMainTableViewModel BuildSut() {
    return null;
  }
}
