package org.jabref.vimotest.MainTableTests;

/*Generated by MPS */


import org.jabref.gui.util.uithreadaware.UiThreadInvoke;

public class JabRefMainTableViewModelTestSetupImpl extends JabRefMainTableViewModelTestSetup {

    private JabRefMainTableViewModelImpl viewModel;

    @Override
    public void Init() {
        UiThreadInvoke.INVOKER = Runnable::run;
        viewModel = new JabRefMainTableViewModelImpl();
    }

    @Override
    public void SetBibFileTestContext(String bibFileContent) {
        viewModel.setBibDatabaseContext(bibFileContent);
    }

    @Override
    public JabRefMainTableViewModel BuildSut() {
        return viewModel;
    }
}
