package org.jabref.vimotest.MainTableTests;

/*Generated by MPS */


public class JabRefMainTableViewModelTestSetupImpl extends JabRefMainTableViewModelTestSetup {

    private JabRefMainTableViewModelImpl viewModel;

    @Override
    public void Init() {
        viewModel = new JabRefMainTableViewModelImpl();
    }

    @Override
    public void SetBibFileTestContext(String bibFileContent) {
        viewModel.setBibDatabaseContext(bibFileContent);
    }

    @Override
    public JabRefMainTableViewModel BuildSut() {
        return viewModel;
    }
}
