package org.jabref.vimotest.MainTableTests;

/*Generated by MPS */

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import java.util.List;
import org.junit.jupiter.api.Assertions;

public class JabRefMainTableViewModelTests_Test {
  private JabRefMainTableViewModel sut;
  private JabRefMainTableViewModelTestSetup testSetup;
  private String file = "@Article{MyArticle,\n  author={My Author},\n  title={My Title},\n  year={2025},\n  ranking={rank1},\n  readstatus={read},\n  priority={prio1}\n}";
  @Test
  public void test_Default_given_file_when_LoadView_then_Entries_has_1_rows() throws Exception {
    this.given_file();
    this.BuildSut();
    this.when_LoadView();
    this.then_Entries_has_1_rows();
  }
  @BeforeEach
  public void setUp() {
    this.testSetup = new JabRefMainTableViewModelTestSetupImpl();
    this.testSetup.Init();
  }



  protected void BuildSut() {
    this.sut = this.testSetup.BuildSut();
  }



  public void given_file() {
    this.testSetup.SetBibFileTestContext(this.file);
  }


  public void when_LoadView() {
    this.sut.loadView();
  }


  public void then_Entries_has_1_rows() {
    List<JabRefMainTableViewModelEntriesRow> actualRows = this.sut.getEntriesTableRows();
    Assertions.assertEquals(1, actualRows.size());
    // {
    JabRefMainTableViewModelEntriesRow row0 = actualRows.get(1 - 1);
    Assertions.assertEquals("Article", row0.getColumnCellLabelText());
    Assertions.assertEquals("My Author", row0.getAuthorLabelText());
    Assertions.assertEquals("My Title", row0.getTitleLabelText());
    Assertions.assertEquals("2025", row0.getYearLabelText());
    Assertions.assertEquals("RANK1", row0.getRankImageName());
    Assertions.assertEquals("READ_STATUS_READ", row0.getReadStatusImageName());
    Assertions.assertEquals("PRIORITY_HIGH", row0.getPriorityImageName());
    // }
  }
}
